### ISSUE TITLE
Completing Web Design System style guide in Figma

### ISSUE THREAD

**Issue by seanlip** [oppia/design-team#16] opened 2022-07-19 06:07 UTC
Things left to do:
- [ ] Transfer over Components (e.g. tooltips, dialogs) and Illustrations to Figma.
- [ ] Ensure all responsive designs are available:
  - [ ] XL Desktop
  - [ ] M Tablet
  - [ ] S Mobile

**Comment by danapj** [comment] 2022-08-30 04:55
Hi @findimue @fionafyzeng i would like to discuss if UXW can get involved in this so we can help create buttons etc with standardised strings? This will also help document some of the changes we've made (e.g. to deprecate the term 'chapters') into the design system as a whole. Lmk :) Thanks!

**Comment by fionafyzeng** [comment] 2022-09-20 00:43
SEP 8: Chantel Chan (CC) requested help with transferring AdobeXD Android mocks into Figma, since she will be beginning her new job as of today Sep 19. New UXD Yan Xu (YX) is eager to take on this task.

CC's availability: 
- Monday or Tuesday: 4 PM ~ 6 PM 
- Thursday or Friday: 8 AM ~ 9 AM or 4 PM ~ 5 PM

@findimue will be discussing this with YX tonight Sep 19 at 7:30pm about completing this first task: Transfer over Components (e.g. tooltips, dialogs) and Illustrations to Figma.

**Comment by ghost** [comment] 2022-09-20 18:02
I added the AdobeXD to Figma project as a separate issue.

**Comment by ghost** [comment] 2022-09-20 18:19
@danapj Yes, I think it makes sense for UXW to get involved in updating the Design Style Guide in [Figma](https://www.figma.com/file/nrQrOxSxSg1oabuVE6XJpa/Oppia-Design-Guide?node-id=297%3A3656). We are still identifying how to establish a changelog for the Design Style Guide, so once we have that in place and changes can be documented, we can establish a process for UXW. I will endeavor to resolve the changelog issue by Sunday, 9/25.

**Comment by dchen97** [comment] 2022-11-16 22:31
What exactly is the status of this project? Is there a deadline / ETA associated with this?

**Comment by seanlip** [comment] 2023-01-13 15:11
@kaiyuxu I wonder if we can close this issue -- could you please look over it and see if there's anything here that we should include in the Web style guide amendments?

Also, it might be worth syncing up with @danapj about this comment: https://github.com/oppia/design-team/issues/16#issuecomment-1231139803

**Comment by kaiyuxu** [comment] 2023-01-17 03:21
@seanlip I think Chantel confirmed that the Adobe XD designs have been incorporated into the Figma file. We have responsive design components for mobile, tablets, and Desktops. According to Chantel and what I observed from inspecting our website, we auto-scaled fonts so for that we don't have a defined design guide.  

@danapj Do you want to connect on your comment about involving a UXW process in the design style guide? I can schedule a meeting based on your availability. Thanks!

**Comment by danapj** [comment] 2023-01-18 02:23
hey kaiyu! I'll let @roxanashirazi weigh on this one -- she will be covering issues related to a content design system

**Comment by seanlip** [comment] 2023-01-23 09:26
@roxanashirazi Friendly ping -- did you see this?

**Comment by ghost** [comment] 2023-01-23 12:47
@seanlip Thank you for the follow-up!

@kaiyuxu I'll email you to schedule a meeting

**Comment by kaiyuxu** [comment] 2023-03-06 03:04
Follow up questions: 

- [x] Do we have a standard for applying shadow on the design elements eg. cards? Same as the corner roundness, eg. input box.
- [x] Tooltips - What is the size of the text used on the tooltip? Same as regular text size 18px?
- [x] I think we should add one color on the color palette to indicate an error message or color used on the delete button. We got a delete button on the button style sheet, but the color was not included in the palette.
- [x] Add guidance on button arrangement in modals.

**Closed as completed** 2023-05-14 23:24 UTC
Labels: Design System
