### ISSUE TITLE
Figma design issue on Footers

### ISSUE THREAD

**Issue by smtirike02** [oppia/design-team#148] opened 2024-04-12 14:41 UTC
Hi, In the **[Oppia.org's](https://www.figma.com/file/STgAK3PxJz3qxoljrTPy2U/Web-Style-Guide-%3E-2023-%3E-Aug?type=design&node-id=0%3A1&mode=design&t=JM691YNC4kSlhBPT-1)**  Figma I noticed that there's a collision on Footers section. Both components for footer and banners are unreadable making it confusing. I'd be happy to fix the issue if needed help!

![Screenshot 2024-04-12 at 15 35 06](https://github.com/oppia/design-team/assets/121672080/476cdbfc-93fb-4e0b-a44a-0a4a35b98a3e)

**Comment by smtirike02** [comment] 2024-04-19 11:38
Hi, any updates on this issue?  @seanlip @dchen97

**Comment by seanlip** [comment] 2024-04-19 11:44
Hi @smtirike02 I think this is a question for @qluuu and @celestinetales, who lead the design systems team. Looping them in. Thanks!

**Comment by qluuu** [comment] 2024-04-20 03:01
@smtirike02 @seanlip Thanks for looping us in! Yes, the readability is definitely an issue. As this the Aug 2023 Design System File, I don't have edit access to this file. Would be happy to edit if granted access. 

Also, @seanlip, as the new design system file gets more pages finalized, it would be helpful to make a note on this Aug 2023 file to point designers/dev to the new file as well.

**Comment by seanlip** [comment] 2024-04-20 13:30
Hi @qluuu, you are now an editor of the file. Please feel free to make the necessary changes. @celestinetales is the owner so please reach out to both of us if you run into any issues.

Also, we should update the links at https://github.com/oppia/design-team to point to the canonical reference. Could you please tell me if an update is needed there, and if so, what the new link(s) should be? 

Thanks!

**Comment by qluuu** [comment] 2024-04-24 22:54
@seanlip Thanks for adding me. I'll work on this #148 Footers project edits at the end of the week. 

Re: canonical reference, yes we can update it soon. But since our new design system is still very much a work in progress, I think first we need to paste all the items from the old file that we haven't worked on yet (items still in status quo) into our new canonical file and put appropriate status annotations (e.g., "Most current version: Please use this version in your designs, MM/DD/YYYY") to ensure that anyone looking at the file isn't confused. I anticipate this to be a fairly quick process. Let me know what you think. Thanks!

**Comment by seanlip** [comment] 2024-04-25 05:14
@qluuu Hmm, what do you think about just treating the existing reference as the canonical one, and updating it as needed? And, any approach that enables designers to know what to do and what they can rely on as solid works for me. Perhaps this is something worth discussing with the team?

**Comment by qluuu** [comment] 2024-04-26 22:09
@seanlip The existing reference has all design system info on one page. In our new system template, the structure is different. We have separate pages for different assets so that it's easier to load and so that designers can find things easily. I can definitely discuss with team on Monday and loop you in during the Leads meeting.

**Comment by seanlip** [comment] 2024-06-21 08:49
@qluuu Do you know what the next steps are for this issue? The comment above said that you would follow up after discussing with the team, but I am not sure what the outcome of the discussion is.

**Comment by qluuu** [comment] 2024-06-24 23:21
@seanlip Hi Sean, according to the team, they refer to both the 2023 design system and the new template when designing and that it was useful to see what the past design system looks like, especially as we are still updating sections the new template. In terms of record keeping, it was useful to see how the design system has evolved. 

Based on this, for the new template, I've pasted the relevant frames from the Aug 2023 design system file into our new template version with clear labeling that "this is the 2023 version that is still in use while we are pending updates". In the case of sections that have been updated (e.g., typography) I've included a note saying, in essence, "this is updated 2024 version and is currently in use for UX designers." I just need to run this format by the team to get their final thoughts.

**Comment by seanlip** [comment] 2024-06-25 17:38
Sounds good, thanks @qluuu. In that case, let's try and standardize on a single source of truth as discussed in the design leads meeting -- feel free to update this issue once we have a confirmed canonical-source-of-truth file, so that we can make sure we reflect it in all our documentation, and then close this issue.

Thanks!

**Comment by qluuu** [comment] 2024-08-27 01:02
@seanlip Just to follow-up here with a comment for record keeping. This issue can indeed be closed. The overlap of text was fixed in the old design system file ([Aug 2023 Design System Figma File](https://www.figma.com/design/STgAK3PxJz3qxoljrTPy2U/Web-Style-Guide-%3E-2023-%3E-Aug?node-id=0-1&t=rYCtBqSMN7T7Sq4n-1)) and this change is also reflected in the [new design system file](https://www.figma.com/design/MOnLoR43wqVrxjBrN8oKj1/Oppia-Design-System-Template?node-id=35086-4501&t=Kz7fIBjsYq9qTpoX-1).

**Comment by seanlip** [comment] 2024-08-27 03:27
Great, thanks @qluuu! Closing this then.

**Closed as completed by seanlip** 2024-08-27 03:27 UTC
