### ISSUE TITLE
[Transferred from Web repo] [BUG]: Overlapping of Oppia image and language translate button on Terms Of Service page

### ISSUE THREAD

**Issue by ATULPOP** [oppia/design-team#121] opened 2023-12-27 06:55 UTC
### Describe the bug

The image and button are overlapping over each other in the Galaxy Fold dimensions.
![image](https://github.com/oppia/oppia/assets/149944292/851bfb82-bf6a-4642-8f6d-3214f33f4b30)

### URL of the page where the issue is observed.

https://www.oppia.org/terms

### Steps To Reproduce

1) Go to https://www.oppia.org/terms

### Expected Behavior

They should not overlap each other.

### What device are you using?

Desktop

### Operating System

Windows

### Tips for developers

Before tackling the bug, please use `git bisect` (see https://git-scm.com/docs/git-bisect) to investigate which PR caused it. If the issue occurred before commit https://github.com/oppia/oppia/commit/c7db0fe, the most effective approach is to utilize the [Python setup](https://github.com/oppia/oppia/wiki/Installing-Oppia/718fd4d0d9ba801142c02e98a499db26ed852c54) for conducting a `git bisect` (You only need to go back as far as commit https://github.com/oppia/oppia/commits/9a334e9). If you need to perform a `git bisect` for any commit beyond that commit, the Docker setup will be suitable. If you find the PR, leave a comment on this issue pointing to it, or just say that it happened before commit 9a334e9 if you could reproduce it there. This will help us fix the issue by reverting the faulty PR.

Also, if this is your first issue, please make sure to follow https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue and https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up before claiming it. Thanks!

**Comment by Baggie220** [comment] 2023-12-27 07:11
Hey I am interested to solve this issue.
On the main page (https://www.oppia.org/) we can see -
![image](https://github.com/oppia/oppia/assets/154577754/84c26805-5de6-4b10-8761-00cc6491c214)

To maintain consistency across the platform, it would be beneficial to replicate a similar styling on the Terms of Service page.
My approach to the issue would be -
1) Go to top-navigation-bar.component.css 
2) Change the margin and styling so that it finally looks like this 
![image](https://github.com/oppia/oppia/assets/154577754/b793c674-a960-461c-8a78-aeab5a1b761f)

@seanlip @kevintab95 Can you assign this issue to me .I will make the PR with the above approach once the issue gets assigned to me ? Thanks !

**Comment by Vir-8** [comment] 2023-12-27 07:28
Something to note, it's not limited to the terms page and same occurs on the learner dashboard page, maybe a couple other pages too

And on both pages, the language and account buttons just disappear at like 355 px width, when they are supposed to just become smaller

**Comment by Baggie220** [comment] 2023-12-27 08:06
Ya , that is due to the media query applied on the buttons .
![image](https://github.com/oppia/oppia/assets/154577754/2b6de8be-e73f-4c1e-abd8-0251a547f2d8)

**Comment by seanlip** [comment] 2023-12-27 11:07
I think we'll need the design team to weigh in on this. I'll move this issue over to the design board, thanks for reporting.

**Comment by seanlip** [comment] 2024-11-12 08:35
Closing as a duplicate of https://github.com/oppia/design-team/issues/86

**Closed as not planned by seanlip** 2024-11-12 08:35 UTC
